---
- name: Pimcore
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - { role: preinstall, tags: "preinstall" }
    - { role: pimcore, tags: "pimcore" }
    - { role: end, tags: "end" }