---
- name: replace default configration file
  template:
    src: redis.conf
    dest: /etc/redis.cnf
    mode: 0644

- name: resetart apache
  service: name=redis  state=restarted  enabled=yes

- name : Install Pimcore
  shell: cd /data/wwwroot ; COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/demo-ecommerce pimcore

- name: replace my.cnf
  template:
    src: my.cnf
    dest: /etc/my.cnf
    mode: 0644
  notify: restart mysql

- name: restart mysql
  service:
    name: mysqld
    state: restarted
    enabled: yes

- name: replace vhost.conf
  template:
    src: vhost.conf
    dest: /etc/httpd/vhost/vhost.conf
    mode: 0644

- name: resetart apache
  service: name=httpd  state=restarted  enabled=yes

- name: Initialization Install
  shell: /data/wwwroot/pimcore/vendor/bin/pimcore-install --admin-username admin --admin-password admin123 --mysql-username pimcore --mysql-password "{{mysql_root_password}}" --mysql-database pimcore --no-interaction

- name: delete extra file
  shell: |
    rm -rf /root/*
    rm -rf /data/wwwroot/www.example.com